version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
  - dependency-name: brakeman
    versions:
    - 5.0.0
  - dependency-name: simple_form
    versions:
    - 5.0.3
